#!/usr/bin/env bash

v=$(git describe --exact-match --tags HEAD 2> /dev/null)
if ! [ "$?" = "0" ]; then
  v=$(git rev-parse HEAD 2> /dev/null)
fi

s="\
// Code generated by version.sh. DO NOT EDIT.

package main

const version = \"dev-$v\"\
"

echo "$s" > version.go
