language: go
go: 1.9
services: docker
notifications:
  email: false
addons:
  apt:
    packages: python3-pip
env:
  - STAGE=CLIENT
  - STAGE=API
  - STAGE=DISCORD
before_install: mv client/* ./ && rmdir client
script: ./.travis/build.sh
after_success: ./.travis/deploy.sh
