notifications: {email: false}
matrix:
  include:
    - name: Client
      language: go
      go: 1.11
      before_script:
        - cd client
        - curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
        - unzip awscli-bundle.zip
        - ./awscli-bundle/install -i "$HOME/aws" -b "$HOME/bin/aws"
        - rm -rf awscli-bundle awscli-bundle.zip
        - export PATH=$HOME/bin:$PATH
        - aws s3 sync s3://unnoticed-test ./data
      script: go test -v -cover
      after_script: diff -u <(echo -n) <(gofmt -d .)
    - name: API
      language: python
      python: 3.6
      services: postgresql
      before_script:
        - cd api
        - psql -c 'CREATE DATABASE postgres' -U postgres
        - pip install pipenv
        - pipenv install --dev
      script: pipenv run pytest
      after_script: pipenv run black api --check
