service: unnoticed-api

provider:
  name: aws
  runtime: python3.6

environment:
  PGHOST: ${env:PGHOST}
  PGUSER: ${env:PGUSER}
  PGPASSWORD: ${env:PGPASSWORD}
  PGDATABASE: ${env:PGDATABASE}

functions:
  get_score_hashes:
    handler: api.handlers.get_score_hashes
    events:
      - http:
          method: get
          path: client/get_score_hashes
  put_scores:
    handler: api.handlers.put_scores
    events:
      - http:
          method: post
          path: client/put_scores
  get_scores:
    handler: api.handlers.get_scores
    events:
      - http:
          method: get
          path: api/get_scores
  get_user_best:
    handler: api.handlers.get_user_best
    events:
      - http:
          method: get
          path: api/get_user_best
  get_user_recent:
    handler: api.handlers.get_user_recent
    events:
      - http:
          method: get
          path: api/get_user_recent
  mapset_maintenance:
    handler: api.handler.mapset_maintenance
    events:
      - schedule: rate(8 hours)

plugins:
  - serverless-python-requirements
